import Config

# Configure your database
config :whispr_calls, WhisprCalls.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "whispr_calls_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :whispr_calls, WhisprCallsWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  # check_origin: false uniquement en dev pour ne pas casser le tooling local
  # (Expo web sur des ports varies, curl, Postman). En prod, l'override MFA
  # dans WhisprCallsWeb.Endpoint.ws_check_origin/1 prend le relais via
  # CORS_ALLOWED_ORIGINS (WHISPR-1354).
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "9hbMXc8yxWRk4UEbWIRhmTY6QAYeboXth19QRLR5YgwjpaY69ckOxQr437T2DuuM",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :whispr_calls, dev_routes: true

# Use the in-process Stub for messaging-service membership checks in dev:
# we don't always have a reachable messaging-service. Prod wires the HTTP
# client in config/runtime.exs.
config :whispr_calls, messaging_client: WhisprCalls.Grpc.MessagingClient.Stub

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
