defmodule WhisprCallsWeb.Endpoint do
  @moduledoc """
  Phoenix Endpoint for the WhisprCalls application.

  Sert le HTTP REST `/calls/...` et le WebSocket de signaling `/calls/ws`.
  """

  use Phoenix.Endpoint, otp_app: :whispr_calls

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_whispr_calls_key",
    signing_salt: "yeEAgY7W",
    same_site: "Lax"
  ]

  # socket "/live", Phoenix.LiveView.Socket,
  #   websocket: [connect_info: [session: @session_options]],
  #   longpoll: [connect_info: [session: @session_options]]

  # check_origin est resolu a runtime via {Mod, Fun, Args} pour reutiliser la
  # whitelist CORS_ALLOWED_ORIGINS en prod (WHISPR-1354). En dev/test la
  # fonction renvoie true (permissive) pour ne pas casser le tooling local.
  socket "/calls/ws", WhisprCallsWeb.UserSocket,
    websocket: [
      check_origin: {__MODULE__, :ws_check_origin, []}
    ],
    longpoll: false

  @doc """
  WebSocket origin check (WHISPR-1354).

  Invoque par Phoenix en MFA a chaque connexion avec le `%URI{}` de la requete.

  - En `:prod`, seules les origins listees dans `CORS_ALLOWED_ORIGINS`
    (separees par virgule) sont acceptees. Une valeur absente, vide ou un
    wildcard `*` provoque une erreur — on refuse de booter un transport WS
    permissif en prod sur le signaling LiveKit.
  - En `:dev`/`:test`, renvoie `true` (permissive) pour garder le tooling
    local et les tests fonctionnels sans config supplementaire.
  """
  @spec ws_check_origin(URI.t()) :: boolean()
  def ws_check_origin(%URI{} = uri) do
    case Application.get_env(:whispr_calls, :env) do
      :prod ->
        prod_origin_allowed?(uri)

      _ ->
        true
    end
  end

  defp prod_origin_allowed?(%URI{} = uri) do
    case System.get_env("CORS_ALLOWED_ORIGINS") do
      nil ->
        raise "CORS_ALLOWED_ORIGINS must be set in production for WebSocket origin check (WHISPR-1354)"

      "" ->
        raise "CORS_ALLOWED_ORIGINS cannot be empty in production for WebSocket origin check (WHISPR-1354)"

      "*" ->
        raise "CORS_ALLOWED_ORIGINS=* is not allowed for WebSocket origin check in production (WHISPR-1354)"

      value ->
        origins =
          value
          |> String.split(",")
          |> Enum.map(&String.trim/1)
          |> Enum.reject(&(&1 == ""))

        origin_string = build_origin_string(uri)
        origin_string in origins
    end
  end

  defp build_origin_string(%URI{scheme: scheme, host: host, port: port})
       when is_binary(scheme) and is_binary(host) do
    base = "#{scheme}://#{host}"

    cond do
      is_nil(port) -> base
      scheme == "https" and port == 443 -> base
      scheme == "http" and port == 80 -> base
      true -> "#{base}:#{port}"
    end
  end

  defp build_origin_string(_), do: ""

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :whispr_calls,
    gzip: not code_reloading?,
    only: WhisprCallsWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :whispr_calls
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Exposes /metrics for Prometheus scraping.
  plug PromEx.Plug, prom_ex_module: WhisprCalls.PromEx

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    body_reader: {WhisprCallsWeb.Plugs.RawBodyReader, :read_body, []},
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  plug WhisprCallsWeb.Plugs.Cors

  plug WhisprCallsWeb.Router
end
